# --- CORE PLAYBACK ---
SPACE       cycle pause
RIGHT       seek  5
LEFT        seek -5
UP          add volume 5
DOWN        add volume -5

# --- PLAYLIST & FOLDERS ---
Ctrl+RIGHT  playlist-next
Ctrl+LEFT   playlist-prev
p           script-binding uosc/playlist


# --- UOSC UI BINDS ---
# These explicitly trigger the uosc visual menus
m           script-binding uosc/menu
tab         script-binding uosc/toggle-ui
/           script-binding uosc/keybinds

# --- WINDOW & SYSTEM ---
f           cycle fullscreen
q           quit
ESC         quit