hwdec=auto-copy
gpu-api=d3d11
ao=wasapi
ytdl-format=bestvideo[height<=1080][vcodec^=vp9]+bestaudio/bestvideo[height<=1080][vcodec^=avc]+bestaudio/best

[extension]
no-video
<<<<<<< SEARCH line=1
ytdl-format=bestvideo[height<=1080][vcodec^=vp9]+bestaudio/bestvideo[height<=1080][vcodec^=avc]+bestaudio/best
=======
hwdec=auto-copy
gpu-api=d3d11
ao=wasapi
ytdl-format=bestvideo[height<=1080][vcodec^=vp9]+bestaudio/bestvideo[height<=1080][vcodec^=avc]+bestaudio/best

[extension]
no-video
